/**
 * @file monoid_congruences.h
 * @brief
 * Computations of congruences on monoids. Deterministic hierarchies.
 */


#ifndef CONGRUENCES_H
#define CONGRUENCES_H

#include <stdbool.h>
#include <stdlib.h>
#include "type_dlist.h"
#include "sep_group.h"
#include "nfa.h"
#include "nfa_intersec.h"
#include "monoid.h"
#include "monoid_ideals.h"
#include "monoid_props.h"

 /******************************/
 /* Computation of congruences */
 /******************************/

/**
 * @brief
 * Computation of the least congruence that contains a given partition.
 *
 * @remark
 * The partition is given a a union-find partition which is made into the congruence by
 * the function.
 */
void compute_leastcong(morphism*, //!< The morphism.
    ufind*                     //!< The union-find partition.
);

/***************************************/
/* Partitions generated by an equation */
/***************************************/

/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * BPol(MOD) equation.
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical BPol(MOD)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_bpolmod_mono(morphism* //!< The morphism.
);

/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * BPol(GR) equation (block group).
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical BPol(GR)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_blockg_mono(morphism* //!< The morphism.
);

/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * BPol(DD) equation (Knast).
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical BPol(DD)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_knast_mono(orbits* //!< The DD-orbits.
);


/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * BPol(MOD⁺) equation (Knast on the MOD-kernel).
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical BPol(MOD⁺)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_qknast_mono(orbits*, //!< The MOD⁺-orbits
    subsemi*                //!< The MOD-kernel.
);


/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * MPol(C)-equation. Takes the canonical C-congruence as input.
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical MPol(C)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_mpolc_mono(morphism*, //!< The morphism.
    parti*                     //!< The canonical C-congruence.
);

/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * LPol(C)-equation. Takes the canonical C-congruence as input.
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical LPol(C)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_lpolc_mono(morphism*, //!< The morphism.
    parti*                     //!< The canonical C-congruence.
);

/**
 * @brief
 * Returns the equivalence obtained by identifying the elements which should be equal according to the
 * RPol(C)-equation. Takes the canonical C-congruence as input.
 *
 * @remark
 * Should be combined with the function "compute_leastcong" to compute the canonical RPol(C)-congruence
 * of the morphism.
 *
 * @return
 * The equivalence given as a union-find partition.
 */
ufind* iden_rpolc_mono(morphism*, //!< The morphism.
    parti*                     //!< The canonical C-congruence.
);

/******************************************************************/
/* Computing the level of a language in a deterministic hierarchy */
/******************************************************************/

/**
 * @brief
 * Computes the level of a syntactic morphism in the MPol(C)-hierarchy: C = 1, MPol(C) = 2,...
 *
 * @remark
 * Details of the computation can be displayed on an input stream. It should be set to NULL if
 * no details are desired.
 *
 * @return
 * The level.
 */
short hdet_mpol_level(morphism*, //!< The morphism.
    ufind*,                //!< The canonical C-congruence.
    FILE*                     //!< The stream.
);

// Calcul du niveau dans les hiéarchies LPol/RPol de base C: 1 = RPol(C),LPol(C) 2 = RPol₂(C),LPol₂(C)...
/**
 * @brief
 * Computes the levels of a syntactic morphism in the LPol(C) and the RPol(C)-hierarchies: RPol(C),LPol(C) = 1, RPol₂(C),LPol₂(C) = 2...
 *
 * @remark
 * Details of the computation can be displayed on an input stream. It should be set to NULL if
 * no details are desired.
 *
 * @attention
 * The levels are returned using pointers
 */
void hdet_lrpol_level(morphism*, //!< The morphism.
    ufind*,                 //!< The canonical C-congruence.
    FILE*,                   //!< The stream.
    short*,                  //!< Pointer used to return the level in the LPol hierarchy.
    short*                    //!< Pointer used to return the level in the RPol hierarchy.
);

#endif
